### PR TITLE
Added script to work on power system

### PR DESCRIPTION
**Pull request by genisysram**
Hi 
This is contribution to your code for work on power systems.
Please accept the request

### CODE REVIEW

**Comment by genisysram** [comment]
This also ensures that whatever versions of go you are using is complete and supports all features on ppc64le. And, it is possible for go programs to be architecture dependent - if someone ever adds a dependency on the hardware, expected or not, this will ensure that the project will always build when it gets to the distros - if not, the distro porting team winds up picking up the work which can be painful to those coming in from outside the project.

**Comment by genisysram** [comment]
@grokify 
Please respong to this pull request.

**Comment by grokify** [comment]
@genisysram I accepted this PR, but Travis CI is undergoing some changes so I've added support for GitHub Actions along with Travis CI. Is it possible to support this with GitHub Actions?

**Comment by genisysram** [comment]
Right now , I'm working on Travis , in future If I work on GitHub Actions , I will definitely test this repository.

**Pull request merged**
